autopkg/jaharmi-recipes

Tynsoe/GeekTool.download.recipe
Various clients were getting timeout errors using plain http protocol.
When switched to https they worked again. (It is noted that the URL
listed in the current version of the app v3.1.3’s Info.plist still
shows plain http, but perhaps that will change?)
=> Changed SPARKLE_FEED_URL to use https

DeployStudio/DeployStudioURLProvider.py, Gaucho/XRGURLProvider.py, ObjectiveDevelopment/LaunchBar5URLProvider.py, Oracle/OracleJava7JDKURLProvider.py
In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later (including `urllib2` and `urlparse` in OracleJava7JDKURLProvider.py), but this should catch the low-hanging fruit right now.
I know some processors (like OracleJava7JDKURLProvider.py) may no longer be in use, but I'll let you decide when/if to deprecate those processors and related recipes.
=> Basic python3 compatibility

Bahoom/HyperSwitch.pkg.recipe
Before:
```
The following recipes failed:
HyperSwitch.pkg
Error in com.github.jaharmi.pkg.HyperSwitch: Processor: PkgCreator: Error: Invalid version component "588-dev"
```
After:
```
The following packages were built:
Identifier              Version  Pkg Path                                                                                      
----------              -------  --------                                                                                      
com.bahoom.HyperSwitch  0.2.588  ~/Library/AutoPkg/Cache/com.github.jaharmi.pkg.HyperSwitch/HyperSwitch-0.2.588.pkg  
```
=> Added VersionSplitter processor to fix error in HyperSwitch.pkg.recipe

Inform/Inform.download.recipe
The latest Inform7 now has a previous regex-busting "-Interim" postfix, and has changed where the DMGs are hosted (different URL-space from the download page).
=> Update to inform7 download URL

ECzarny/Spectacle.download.recipe
As of [AutoPkg 0.6.0](https://github.com/autopkg/autopkg/tree/v0.6.0), it's safe to switch back to the "standard" URLDownloader and URLTextSearcher processors.
=> Switch from CURL* back to URL* processors

AndrewGallant/ripgrep.download.recipe
After completing the recent PR and updating my repo, I noticed that after installing the PKG on a test machine I kept getting an error when trying to run `rg` about being unable to read the binary file.
Looking at the download recipe, it appears there wasn't an `asset_regex` key to ensure the Apple-specific file was downloaded from the available assets.  This addresses that and can confirm it completes successfully.  Output from test:
```
autopkg run ~/Documents/GitHub/jaharmi-recipes/AndrewGallant/ripgrep.download.recipe -vv
Processing /Users/USER/Documents/GitHub/jaharmi-recipes/AndrewGallant/ripgrep.download.recipe...
WARNING: /Users/USER/Documents/GitHub/jaharmi-recipes/AndrewGallant/ripgrep.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. …
```
=> Add ASSET_REGEX input variable for ripgrep to get Apple-specific download

Signal/Signal.download.recipe, Signal/Signal.install.recipe, Signal/Signal.munki.recipe, Signal/Signal.pkg.recipe
The Signal download recipe incorrectly included a static URL for downloading the application.
This set of updates fixes this situation with the following changes.
1. Adding more variables to make some kinds of updates easier and to better enable flexible overrides in the future. This includes URLs, regexes, and other bits of information that may need to be changed over time.
1. Searching for the latest update in a YAML file that appears to be processed by a script on the "https://signal.org/download/macos” download page. This search naïvely uses the URLTextSearcher processor on the YAML file URL. URLTextSearcher is part of the standard AutoPkg processor library. The download recipe does _not_ process the YAML file _as_ YAML data.
1. Finding the disk image for the latest application …
=> Determine latest Signal app by finding its disk image in YAML update file

AndrewGallant/ripgrep.install.recipe, AndrewGallant/ripgrep.pkg.recipe
Addresses #42 
What it says on the ~tin~ commit message, btw also tweaked to remove unnecessary-seeming FileFinder (since Copier processor can already look at glob'd paths)
Pardon these are all one commit if that's annoying/undesired, I can split it out and re-submit if you prefer more granularity in commit history
=> add man page to payload/version number to pkg filename (be nice to Jamf peoples), fix install (by making pkg the parent)

Bungie/AlephOne.MarathonInfinity.pkg.recipe
`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).
=> Adjust PkgCreator arguments

MatthewPalmer/Rocket.download.recipe
This should resolve issue #52 by changing the stale download URL with the new URL.
=> Updated Rocket download URL.

Signal/Signal.pkg.recipe
Removed PathDeleter Processor from com.github.jaharmi.pkg.Signal which seems to be redundant in the newest version of AutoPkg
=> Fix for Issue #61. 

DeployStudio/DeployStudioURLProvider.py, Gaucho/XRGURLProvider.py, ObjectiveDevelopment/LaunchBar5URLProvider.py, Oracle/OracleJava7JDKURLProvider.py
As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …
=> Update Python path in processors to reflect changes in macOS 12.3+

LuckyMarmot/Paw.download.recipe, LuckyMarmot/Paw.install.recipe, LuckyMarmot/Paw.munki.recipe, LuckyMarmot/Paw.pkg.recipe
Looks like the Paw app is now named RapidAPI, but the website and bundle ID and everything is still Paw, so I don't know if we should change the names of the recipes or not. I elected not.
=> Accounting for rebrand to RapidAPI

LuckyMarmot/Paw.download.recipe
Looks like more rebranding changes. This time the URL.
=> Change in Download URL

Nucleobytes/Manuscripts.download.recipe, Nucleobytes/Manuscripts.install.recipe, Nucleobytes/Manuscripts.jss.recipe, Nucleobytes/Manuscripts.munki.recipe, Nucleobytes/Manuscripts.pkg.recipe
Fixes #63 by deprecating recipes for the Manuscript app. The app no longer appears to be available via direct download links or its update feed.
=> Deprecate Manuscript app recipes

Tinrocket/HyperDither.download.recipe, Tinrocket/HyperDither.install.recipe, Tinrocket/HyperDither.jss.recipe, Tinrocket/HyperDither.munki.recipe, Tinrocket/HyperDither.pkg.recipe
Fixes #68  by deprecating recipes for the HyperDither app. The app is apparently available only in the Mac App Store.
=> Deprecate HyperDither app recipes

MaxGoedjen/Secretive.download.recipe
In order to simplify AutoPkg recipe search results, this PR deprecates the Secretive recipes, which are redundant with the ones in the zentral-recipes repo.
=> Deprecate Secretive recipes

PrimateLabs/Geekbench4.download.recipe
This PR adds code signature verification for Geekbench 4.
Here's the CodeSignatureVerifier section of the verbose recipe run output:
```
CodeSignatureVerifier
CodeSignatureVerifier: Verifying code signature...
CodeSignatureVerifier: Deep verification enabled...
CodeSignatureVerifier: Strict verification not defined. Using codesign defaults...
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.jaharmi.download.Geekbench4/Geekbench 4/Geekbench 4.app: valid on disk
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.jaharmi.download.Geekbench4/Geekbench 4/Geekbench 4.app: satisfies its Designated Requirement
CodeSignatureVerifier: ~/Library/AutoPkg/Cache/com.github.jaharmi.download.Geekbench4/Geekbench 4/Geekbench 4.app: explicit requirement satisfied
CodeSignatureVerifier: …
```
=> Add code signature verification for Geekbench 4

Warp/Warp.download.recipe
This PR adjusts the Warp download URL to a non-version-specific one.
Verbose recipe run output:
```
% autopkg run -vvq 'Warp/Warp.download.recipe'
Processing Warp/Warp.download.recipe...
WARNING: Warp/Warp.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLDownloader
{'Input': {'filename': 'Warp.dmg', 'url': 'https://app.warp.dev/download?'}}
URLDownloader: No value supplied for prefetch_filename, setting default value of: False
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Thu, 26 Dec 2024 19:56:52 GMT
URLDownloader: Storing new ETag header: W/"1390777eba718c236302f4d259c1413e"
URLDownloader: Downloaded …
```
=> Fix version-specific Warp download URL

Plethra/AudioAcaciaServer.download.recipe
The Plethra website appears to be offline. This PR deprecates the Plethra audio|acacia:server recipes.
=> Deprecate Plethra recipes

BalanceOpen/BalanceOpen.download.recipe
The BalanceOpen software is no longer available for download, and the associated GitHub repo hasn't been updated in 6 years and has no release assets available. This PR deprecates the BalanceOpen recipes.
=> Deprecate BalanceOpen recipes

Rue/ControlPlane.download.recipe
This PR updates the method used to download the ControlPlane app, since the Sparkle feed appears to be offline. It also adds code signature verification to ensure the integrity of the resulting download.
```
% autopkg run -vvq 'Rue/ControlPlane.download.recipe'
Processing Rue/ControlPlane.download.recipe...
WARNING: Rue/ControlPlane.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
GitHubReleasesInfoProvider
{'Input': {'github_repo': 'dustinrue/ControlPlane'}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, …
```
=> Fix ControlPlane recipes and add code signature verification

DeployStudio/DeployStudio.download.recipe
😢 DeployStudio is no longer under active development ([details](https://deploystudio.com/)). This PR deprecates the DeployStudio recipes.
=> Deprecate DeployStudio recipes

DEVONTechnologies/CalcService.DEVONTechnologies.download.recipe, DEVONTechnologies/Freeware.DEVONTechnologies.download.recipe, DEVONTechnologies/WordService.DEVONTechnologies.download.recipe
This PR updates the download method used to retrieve freeware downloads from the DEVONTechnologies site.
Verbose recipe run output:
```
% autopkg run -vvq 'DEVONTechnologies/WordService.DEVONTechnologies.download.recipe' 'DEVONTechnologies/CalcService.DEVONTechnologies.download.recipe'
Processing DEVONTechnologies/WordService.DEVONTechnologies.download.recipe...
WARNING: DEVONTechnologies/WordService.DEVONTechnologies.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="(https://download\\.devontechnologies\\.com/download/freeware/wordservice/[\\d\\.]+/WordService\\.app\\.zip)"',
'request_headers': {'user-agent': 'Mozilla/5.0 (Macintosh; Intel '
'Mac OS X 10_15_7) '
'AppleWebKit/605.1.15 (KHTML, …
```
=> Fix DEVONTechnologies freeware recipes

Bay12Games/DwarfFortress.download.recipe
This PR updates the download page and file pattern for DwarfFortress. (Although note that the Mac version is no longer under active development.)
Verbose recipe run output:
```
% autopkg run -vvq 'Bay12Games/DwarfFortress.download.recipe'
Processing Bay12Games/DwarfFortress.download.recipe...
WARNING: Bay12Games/DwarfFortress.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="(df_[\\d_]+_osx\\.tar\\.bz2)"',
'result_output_var_name': 'FILE_DOWNLOAD_URL',
'url': 'https://www.bay12games.com/dwarves/older_versions.html'}}
URLTextSearcher: Found matching text (FILE_DOWNLOAD_URL): df_47_05_osx.tar.bz2
{'Output': {'FILE_DOWNLOAD_URL': 'df_47_05_osx.tar.bz2'}}
URLDownloader
{'Input': {'url': …
```
=> Fix DwarfFortress recipes
